FROM python:latest
RUN apt-get update
RUN apt-get -y upgrade
RUN pip install --upgrade pip
RUN pip install flask
RUN pip install requests
RUN pip install itsdangerous
RUN pip install Flask-MySQLdb
RUN pip install psycopg2
RUN pip install mariadb
WORKDIR /flaskProject
CMD ["python", "app.py"]
